library(geoR)
source("altitud.r")
par(mfrow = c(1,2))
plot(altitud$x,altitud$y,pch=20,xlab="longitud",ylab="latitud")
plot(altitud$x,altitud$y,type="n",xlab="longitud",ylab="latitud")
text(altitud$x,altitud$y,altitud$alt,cex=0.6)
par(mfrow = c(1,1))
library(geoR)
alti.geo <- as.geodata(altitud)
plot.geodata(alti.geo)
altiu.vari <- variog(alti.geo, option = "cloud")
plot(altiu.vari)

alti.v1 <- variog(alti.geo, uvec=seq(0, 6, 1.2), messages = F)
plot(alti.v1, pch=20)


alti.exp.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),messages=F)
alti.sph.ml<-likfit(geodata = alti.geo, ini = c(6000, 6), cov.model="sph",messages=F)
alti.mat.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="mat",kappa=1.5,messages=F)
alti.mat2.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="mat",kappa=1,fix.nugget=F,messages=F)
alti.cir.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="cir",messages=F)
#alti.gau.ml<-likfit(geodata = alti.geo, ini = c(500000, 50),cov.model="gau")
alti.cub.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="cub",messages=F)
alti.pow.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="powered.exponential",kappa=1.75,messages=F)
alti.pow2.ml<-likfit(geodata = alti.geo, ini = c(6000, 6),cov.model="powered.exponential",kappa=1.75,fix.nugget=F,messages=F)
plot(alti.v1)
lines(alti.pow2.ml,max.dist=250,lwd=3,col='red')
lines(alti.mat2.ml,max.dist=250,lwd=3,col='blue')
lines(alti.pow.ml,max.dist=250,lwd=3,col='green')
lines(alti.mat.ml,max.dist=250,lwd=3,col='yellow')
lines(alti.cub.ml,max.dist=250,lwd=3,col='orange')
#lines(alti.gau.ml,max.dist=250,lwd=3,col='cyan')
lines(alti.cir.ml,max.dist=250,lwd=3,col='grey')
lines(alti.exp.ml,max.dist=250,lwd=3,col='magenta')
lines(alti.sph.ml,max.dist=250,lwd=3,col='pink')

